/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 28-Feb-2025 12:32:47
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 4
 * 稳定     : 是
 * 线性相位   : 否
 */
#ifndef __FDACOEFS_H__
#define __FDACOEFS_H__
/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
#include "main.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Matlab2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
#define MWSPT_NSEC 9

extern const int NL[MWSPT_NSEC];  
extern const real64_T NUM_1K[MWSPT_NSEC][3];
extern const real64_T NUM_250[MWSPT_NSEC][3];
extern const int DL[MWSPT_NSEC];
extern const real64_T DEN_1K[MWSPT_NSEC][3];
extern const real64_T DEN_250[MWSPT_NSEC][3];

typedef struct _Biquad{
	real64_T b0, b1, b2;
	real64_T a1, a2;
	real64_T x1, x2;
	real64_T y1, y2;
}Biquad;
typedef struct _IIRFilter{
	Biquad sections[MWSPT_NSEC];
}IIRFilter;

void IIRFilter_Init(IIRFilter *filt, const real64_T NUM[MWSPT_NSEC][3], const real64_T DEN[MWSPT_NSEC][3]);
real64_T  IIRFilter_Process(IIRFilter *filt, real64_T input);
int Decoder(const void * Input, size_t Len);
void Encoding(const void * Input, uint8_t * Output);
#endif //__FDACOEFS_H__
